# Generated by Django 5.0.1 on 2025-01-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_delete_milestone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Linkedin_link',
            new_name='Live_link',
        ),
    ]
